// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.



/**
* Development environment
*/
export const environment = {
  /**
   * development
   */
  production: false,
  userPolicyPayment: 'anonymouspayment@bupalatinamerica.com',
  passwordPolicyPayment: 'Bupa2019@',
  apiHost: 'https://pf-security-services.bupa.com.mx/User/api/v1',
  issuer: 'https://pf-security-services.bupa.com.mx/Identity/core',
  redirectUri: '',
  responseType: 'id_token token',
  clientId: 'onlineservices_web_client',
  scope: 'openid profile policy provider bupa_profile user agent payment claim claimsubmission enrollment common customer preauthorization medicalquestionary network_provider product medical_code coverage amigosplus_quote finance',
  oidc: true,
  strictDiscoveryDocumentValidation: false,
  //postLogoutRedirectUri: 'https://pre.bupa.com.mx/',
  postLogoutRedirectUri: 'http://localhost:4200/',
  logoutUrl: 'https://pf-security-services.bupa.com.mx/Identity/core/connect/endsession',
  clearHashAfterLogin: true,
  languages: 'SPA;ENG',
  idle: 1800,
  timeout: 60,
  returnUrl: 'https://pre.bupa.com.mx/',
  apiHostAmigosPlus: 'https://pf-services.bupa.com.mx/AmigosPlusNotification/api/v1',
  apiHostCommon: 'https://pf-services.bupa.com.mx/Common/api/v1',
  // apiHostCommon: 'http://localhost:63260/api/v1',
  //apiHostPolicy: 'http://localhost:62509/api/v1',
  // apiHostPolicy: 'http://localhost:62630/api/v1',
  apiHostPolicy: 'http://localhost/Policy/api/v1',
  apiHostProviders: 'https://pf-services.bupa.com.mx/Provider/api/v1',
  apiHostClaims: 'https://pf-services.bupa.com.mx/Claims/api/v1',
  apiHostClaimSubmission: 'https://pf-services.bupa.com.mx/ClaimSubmission/api/v1',
  // apiHostClaimSubmission: 'http://localhost:53484/api/v1',
  claimSubmissionFileTypes: 'image:.jpeg,.jpg,.gif|pdf:.pdf|code:.xml',
  claimSubmissionFileTypesNoXml: 'image:.jpeg,.jpg,.gif|pdf:.pdf',
  interactionsFileTypes: 'image:.jpeg,.jpg,.gif|pdf:.pdf',
  claimSubmissionMaxFileSize: 10,
  claimSubmissionMaxFileQuantity: 100,
  currencyUsdId: 192,
  currencyUsdSymbol: 'USD',
  apiHostAgent: 'https://pf-services.bupa.com.mx/Agent/api/v1',
  paymentHistoricPageSize: 5,
  paymentMethodTypeMex: 'CC',
  paymentMethodTypeGlb: 'CC|Cheque|WT',
  apiHostPolicyApplication: 'https://pf-services.bupa.com.mx/Enrollment/api/v1',
  //apiHostPayments: 'https://pf-services.bupa.com.mx/Payment/api/v1',
  apiHostPayments: 'http://localhost:64990/api/v1',
  staticHtmlFileRoot: 'https://pre.bupa.com.mx/assets',
  apiHostImpersonation: 'https://pf-security-services.bupa.com.mx/Identity/core/connect/token',
  clientIdImpersonation: 'onlineservices_web_client_simple',
  scopeImpersonation: 'user policy bupa_impersonalize bupa_profile claim claimsubmission enrollment common agent provider payment medicalquestionary network_provider product medical_code coverage amigosplus_quote finance',
  authorizationImpersonation: 'Basic b25saW5lc2VydmljZXNfd2ViX2NsaWVudF9zaW1wbGU6YnVwQGludGVyZ3J1cG8=',
  convertDateToken: true,
  googleCaptchaSiteKey: '6Lc8mLcZAAAAAIkBIdn_Nwub2emUmFRZKkfMIQvb',
  clientIdPaymentWithoutLoggin: 'onlineservices_web_client_simple',
  scopePaymentWithoutLoggin: 'payment policy user bupa_profile bupa_anonymous common ',
  numberOfClaimsForEboBundle: 25,
  googleCaptchaSiteKeyInvisible: '6Lc8mLcZAAAAABcJUgE0za1Lgd5B1DMpBH8Ugqzz',
  apiHostCustomer: 'https://pf-services.bupa.com.mx/Customer/api/v1',
  inquiryFileTypes: 'image:.jpeg,.jpg,.gif,.bmp|pdf:.pdf|code:.xml',
  apiHostEventNotification: 'https://pf-services.bupa.com.mx/EventNotification/api/v1',
  apiHostPreAuthorization: 'https://pf-services.bupa.com.mx/ClaimsPreAuthorization/api/v1',
  preAuthFileTypes: 'image:.jpeg,.jpg,.gif,.bmp|pdf:.pdf',
  paymentMethodTypePanama: 'CC',
  changePolicyFileTypes: 'image:.jpeg,.jpg,.gif|pdf:.pdf',
  insuranceResources: 'SPA_41;SPA_56',
  apiHostQuote: 'https://pf-services.bupa.com.mx/Quote/api/v1',
  apiHostChangePortfolio: 'https://pf-security-services.bupa.com.mx/Identity/core/connect/token',
  apiHostMedicals: 'https://pf-services.bupa.com.mx/Questionary/api/v1',
  apiHostQuoteEngine: 'http://localhost:52665/api/v1',
  //apiHostPaymentTransaction: 'https://pf-services.bupa.com.mx/Payment/api/v1',
  apiHostPaymentTransaction: 'http://localhost:64990/api/v1',
  policyAplicationFileTypes: 'image:.jpeg,.jpg,.gif,.bmp|pdf:.pdf',
  networkProvidersFiles: 'code:.xlsx',
  networkProvidersMaxFileSize: 25,
  networkProvidersMaxFileQuantity: 1,
  apiHostNetworks: 'https://pf-services.bupa.com.mx/NetworkProvider/api/v1',
  apiHostProducts: 'https://pf-services.bupa.com.mx/Product/api/v1',
  newBusinessQuotationUrl: 'https://pf-services.bupa.com.mx/AmigosPlusQuotes/',
  ihiBupaInsurances: '45,49,50,51,52,54,59',
  newBusinessQuoteUrlsAuthorized: 'https://186.144.215.62;https://cotizador.bupasalud.com;https://cotizador.bupasalud.com/',
  apiHostCoverages: 'http://pf-services.bupa.com.mx/Coverage/api/v1',
  paymentMethodTypeGblOnlyCC: 'CC',
  subStepInquiry: 'inquiry',
  subStepTelemedicine: 'telemedicine',
  paymentMethodTypeEcuador: 'CC',
  chatbotSource: 'https://oc-cdn-public-eur.azureedge.net/livechatwidget/scripts/LiveChatBootstrapper.js',
  chatbotDataOrgId: '9907c111-29d3-4dd0-add3-fc40009f88e8',
  chatbotDataOrgUrl: 'https://orgb4aecd85-crm4.omnichannelengagementhub.com',
  chatbotDataAppIdEng: '5c810505-0bee-4852-8dab-68f784a09ec4',
  chatbotDataAppIdSpa: 'b5aaadcf-7e48-4fe1-9da8-413daa972b44',
  apiHostCommonCrm: 'https://pf-services.bupa.com.mx/Crm/api/v1',
  // apiHostFinance: 'http://localhost:1287/api/v1',
  apiHostFinance: 'https://pf-services.bupa.com.mx/Finance/api/v1',
  splitRedirectUrl: 'https://onlineservices.bupasalud.com/',
  mexicoCostumerServicePhone: "+1 (888) 688-2872",
  mexicoCostumerServiceMail: "atencionalcliente@bupa.com.mx",
  bglaCostumerServicePhone: "+1 (305) 398-7400",
  bglaCostumerServiceMail: "servicio@bupalatinamerica.com",
  goToHomeTitleCurrentBusiness: "Bupa Global Latinamerica",
  goToHomeTitleOffsideBusiness: "Bupa México",
  authformCurrentBusiness: "AuthorizationFormBGLA.png",
  authformOffsideBusiness: "AuthorizationFormBUPAMX.png",
  providersMail: 'proveedores@bupa.com.mx',
  inactivityMXPortal: '12/28/2022 23:00:00|01/01/2023 23:55:59',
  npsSurveyUrl: "https://bupateescucha.bupa.com.mx/d?a=BUPATRAOLS&amp;i=ES&amp;ca=nunic&amp;v=-1",
  apimHost: 'https://sandbox-apimgt.azure-api.net',
  apimSubscription: 'd90d521804c84fcf86f130a31c5dfdeb'
};

/*
 * In development mode, to ignore zone related error stack frames such as
 * `zone.run`, `zoneDelegate.invokeTask` for easier debugging, you can
 * import the following file, but please comment it out in production mode
 * because it will have performance impact when throw error
 */
// import 'zone.js/dist/zone-error',  // Included with Angular CLI.
