/***
 * Enum with all policy states registered in DB
 */
export enum StatusPolicy {
    ACTIVE = 13,
    PENDING_PAYMENT = 14,
    NOT_RATED_YET =	21,
    CANCELED = 22,
    REJECTED = 23,
    PENDING = 24,
    GRACE_PERIOD = 25,
    EXPIRED = 32,
    LAPSED = 33,
    PENDING_INFORMATION = 34,
    TRIAL =	35,
    APPROVED_BY_SYSTEM = 105,
    PENDING_BY_SYSTEM =	106,
    REJECTED_BY_SYSTEM = 107,
    DEATH_BENEFIT =	109,
    APPROVED_BY_UNDERWRITING = 110,
    PENDING_BY_UNDERWRITING = 111,
    REJECTED_BY_UNDERWRITING = 112,
    OVERRIDDEN_BY_UNDERWRITING = 113,
    PENDING_REINSTATEMENT =	133,
    INCOMPLETE = 280,
    TRANSFERED_TO_PALIC = 328,
    PALIC =	330
}
