import { InfoContactMember } from './info-contact-member';
import { InfoAddressMember } from './info-address-member';
import { Address } from './address';
import { InfoIdentifications } from './info-identifications';
import { MemberExtension } from './member-extension';

export interface Member {
    applicationMemberGuid: string;
    applicationGuid: string;
    firstName: string;
    middleName: string;
    lastName: string;
    dob: Date;
    genderId: number;
    gender: string;
    systemMeasureId: number;
    systemMeasure: string;
    nationalityId: number;
    nationality: string;
    maritalStatusId: number;
    maritalStatus: string;
    relationTypeId: number;
    relationType: string;
    dependentRelationId: number;
    dependentRelation: string;
    ocupationId: number;
    ocupation: string;
    previousPolicyId: number;
    previousMemberId: number;
    contactBaseId: number;
    weight: number;
    height: string;
    fullTimeStudent: boolean;
    schoolName: string;
    usCitizenResident: boolean;
    paternalLastName: string;
    maternalLastName: string;
    countryOfBirthId: number;
    countryOfBirth: string;
    industryId: number;
    industry: string;
    sourceOfFundingId: number;
    sourceOfFunding: string;
    otherSourceOfFunding: string;
    patrimonialLinks: string;
    countryOfResidence?: string;
    countryOfResidenceId?: number;
    memberExtension?: MemberExtension;
}
