// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Bupa.OnlineServices.FunctionalTest.Features.Features_Agent
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("ClaimsSubmission", Description="\tI need to make claims\r\n\tAs a provider user\r\n\tI want to make claims by accepting " +
        "content associated with the terms and conditions", SourceFile="features\\features-Agent\\ClaimsSubmissionAgent.feature", SourceLine=0)]
    public partial class ClaimsSubmissionFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ClaimsSubmissionAgent.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ClaimsSubmission", "\tI need to make claims\r\n\tAs a provider user\r\n\tI want to make claims by accepting " +
                    "content associated with the terms and conditions", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validate online claims agreement", new string[] {
                "ClaimsSubmissionAgent"}, SourceLine=7)]
        public virtual void ValidateOnlineClaimsAgreement()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate online claims agreement", null, new string[] {
                        "ClaimsSubmissionAgent"});
#line 8
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
 testRunner.Given("I need to make claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.When("I am on the Claims Online page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("the system must show the contents associated with the terms and conditions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To decline the online claims agreement", new string[] {
                "ClaimsSubmissionAgent"}, SourceLine=14)]
        public virtual void ToDeclineTheOnlineClaimsAgreement()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To decline the online claims agreement", null, new string[] {
                        "ClaimsSubmissionAgent"});
#line 15
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 16
testRunner.Given("I am on the Claims Online page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
testRunner.When("I\'m decline the terms and conditions the online claims agreement.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
testRunner.Then("the system should redirect back to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void STEP1_POLICYINFORMATIONSuccessfullyCompleted(string servidata, string policynumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ClaimsSubmissionAgent"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("STEP 1 - POLICY INFORMATION successfully completed", null, @__tags);
#line 22
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 23
 testRunner.Given("I am on the Claims Online page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
 testRunner.And("I have already accepted the terms and conditions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.When(string.Format("I insert Date of service received {0} and Polycy Number {1}", servidata, policynumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
 testRunner.And("I click on the search button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.Then("Allow to select a member and  proceed with claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("STEP 1 - POLICY INFORMATION successfully completed, 12-11-2018", new string[] {
                "ClaimsSubmissionAgent"}, SourceLine=31)]
        public virtual void STEP1_POLICYINFORMATIONSuccessfullyCompleted_12_11_2018()
        {
#line 22
this.STEP1_POLICYINFORMATIONSuccessfullyCompleted("12-11-2018", "657428", ((string[])(null)));
#line hidden
        }
        
        public virtual void STEP1_POLICYINFORMATIONPolicyDoesNotExist(string servidata, string policynumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ClaimsSubmissionAgent"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("STEP 1 - POLICY INFORMATION: policy does not exist", null, @__tags);
#line 35
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 36
 testRunner.Given("I am on the Claims Online page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
 testRunner.And("I have already accepted the terms and conditions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.When(string.Format("I insert Date of service received {0} and Polycy Number {1}", servidata, policynumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
  testRunner.But("the policy does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line 40
 testRunner.And("I click on the search button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.Then("I must see a message No se han encontrado resultados para tu busqueda.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("STEP 1 - POLICY INFORMATION: policy does not exist, 12-11-2018", new string[] {
                "ClaimsSubmissionAgent"}, SourceLine=44)]
        public virtual void STEP1_POLICYINFORMATIONPolicyDoesNotExist_12_11_2018()
        {
#line 35
this.STEP1_POLICYINFORMATIONPolicyDoesNotExist("12-11-2018", "100", ((string[])(null)));
#line hidden
        }
        
        public virtual void STEP1POLICYINFORMATIONNoMemberIsSelected(string servidata, string policynumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ClaimsSubmissionAgent"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("STEP 1: POLICY INFORMATION No member is selected", null, @__tags);
#line 49
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 50
 testRunner.Given("I am on the Claims Online page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 51
 testRunner.And("I have already accepted the terms and conditions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.When(string.Format("I insert Date of service received {0} and Polycy Number {1}", servidata, policynumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 53
 testRunner.And("I click on the search button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
  testRunner.But("I do not select a member", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line 55
 testRunner.Then("the Proceed with claim button is not enabled in step one", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("STEP 1: POLICY INFORMATION No member is selected, 12-11-2018", new string[] {
                "ClaimsSubmissionAgent"}, SourceLine=59)]
        public virtual void STEP1POLICYINFORMATIONNoMemberIsSelected_12_11_2018()
        {
#line 49
this.STEP1POLICYINFORMATIONNoMemberIsSelected("12-11-2018", "79", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("STEP 2 - ADD DOCUMENTATION successfully completed", new string[] {
                "ClaimsSubmissionAgent"}, SourceLine=62)]
        public virtual void STEP2_ADDDOCUMENTATIONSuccessfullyCompleted()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("STEP 2 - ADD DOCUMENTATION successfully completed", null, new string[] {
                        "ClaimsSubmissionAgent"});
#line 63
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 64
 testRunner.Given("I am on the step dos add documentation the Claims Online page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 65
 testRunner.When("I added a valid file: pdf of diez MB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
 testRunner.Then("the system should allow me to continue to step tres", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("STEP 2 - ADD DOCUMENTATION: invalid files", new string[] {
                "ClaimsSubmissionAgent"}, SourceLine=68)]
        public virtual void STEP2_ADDDOCUMENTATIONInvalidFiles()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("STEP 2 - ADD DOCUMENTATION: invalid files", null, new string[] {
                        "ClaimsSubmissionAgent"});
#line 69
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 70
 testRunner.Given("I am on the step dos add documentation the Claims Online page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 71
 testRunner.When("I added a invalid file: pdf of once MB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
 testRunner.Then("I must view a message cargue el tipo de archivo apropiado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("STEP 2 - ADD DOCUMENTATION: Do not attach documents", new string[] {
                "ClaimsSubmissionAgent"}, SourceLine=74)]
        public virtual void STEP2_ADDDOCUMENTATIONDoNotAttachDocuments()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("STEP 2 - ADD DOCUMENTATION: Do not attach documents", null, new string[] {
                        "ClaimsSubmissionAgent"});
#line 75
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 76
 testRunner.Given("I am on the step dos add documentation the Claims Online page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 77
 testRunner.But("I did NOT add a file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line 78
 testRunner.Then("the Proceed with claim button is not enabled in step two", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("STEP 2 - ADD DOCUMENTATION: Delete an added file", new string[] {
                "ClaimsSubmissionAgent"}, SourceLine=80)]
        public virtual void STEP2_ADDDOCUMENTATIONDeleteAnAddedFile()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("STEP 2 - ADD DOCUMENTATION: Delete an added file", null, new string[] {
                        "ClaimsSubmissionAgent"});
#line 81
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 82
 testRunner.Given("I am on the step dos add documentation the Claims Online page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 83
 testRunner.When("I added a valid file: pdf of diez MB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 84
 testRunner.And("I delete the added file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
 testRunner.Then("the Proceed with claim button is not enabled in step two", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("STEP 2 - ADD DOCUMENTATION: Delete all added files", new string[] {
                "ClaimsSubmission"}, SourceLine=87)]
        public virtual void STEP2_ADDDOCUMENTATIONDeleteAllAddedFiles()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("STEP 2 - ADD DOCUMENTATION: Delete all added files", null, new string[] {
                        "ClaimsSubmission"});
#line 88
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 89
 testRunner.Given("I am on the step dos add documentation the Claims Online page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 90
 testRunner.When("I added a valid file: pdf of diez MB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 91
 testRunner.And("I delete all added files", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 92
 testRunner.Then("the Proceed with claim button is not enabled in step two", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("STEP 2 - ADD DOCUMENTATION: Validate duplicate files", new string[] {
                "ClaimsSubmissionAgent"}, SourceLine=94)]
        public virtual void STEP2_ADDDOCUMENTATIONValidateDuplicateFiles()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("STEP 2 - ADD DOCUMENTATION: Validate duplicate files", null, new string[] {
                        "ClaimsSubmissionAgent"});
#line 95
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 96
 testRunner.Given("I am on the step dos add documentation the Claims Online page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 97
 testRunner.When("I added a valid file: pdf of diez MB", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 98
  testRunner.But("The file was previously added", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line 99
 testRunner.Then("I must see a modal with a message el archivo es duplicado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("STEP 3 - SUMMARY AND PRESENTATION: Claim New sent successfully", new string[] {
                "ClaimsSubmissionAgent"}, SourceLine=102)]
        public virtual void STEP3_SUMMARYANDPRESENTATIONClaimNewSentSuccessfully()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("STEP 3 - SUMMARY AND PRESENTATION: Claim New sent successfully", null, new string[] {
                        "ClaimsSubmissionAgent"});
#line 103
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 104
 testRunner.Given("I am on the step tres summary and presentation the Claims Online page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 105
 testRunner.When("I click on the submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 106
 testRunner.And("Select the option New claim", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
 testRunner.Then("I must see a modal with a message la información se envió con éxito\\.Su número de" +
                    " confirmación es", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("STEP 3 - SUMMARY AND PRESENTATION: Mexican claim submit without xml file", new string[] {
                "ClaimsSubmissionAgent"}, SourceLine=110)]
        public virtual void STEP3_SUMMARYANDPRESENTATIONMexicanClaimSubmitWithoutXmlFile()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("STEP 3 - SUMMARY AND PRESENTATION: Mexican claim submit without xml file", null, new string[] {
                        "ClaimsSubmissionAgent"});
#line 111
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 112
 testRunner.Given("I am in the summary of step three and I have entered a policy of mexico", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 113
  testRunner.But("I have not added an xml file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line 114
 testRunner.When("I click on the submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 115
 testRunner.Then("I must see a modal with a message La Factura en formato XML es requerida y no ha " +
                    "sido enviada. Favor verificar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
